name: Gatsby Publish
on:
  push:
    branches:
      - main
jobs:
  build_gatsby:
  - name: 😎 Setup Node
  - uses: actions/setup-node@v3
    with:
      node-version: '18.4.0'

  - name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages

